#!/bin/bash

echo "****** Launch test *********"

script_directory=$(dirname $(readlink -f $0))
cd "${script_directory}/cypress"

docker-compose build
docker-compose run cypress npm run cypress-test
docker-compose down
