version: '3.2'

services:
  cypress:
    build:
      context: .
      dockerfile: DockerfileCypress
    command: npm run cypress-watch
    volumes:
      - ./cypress-visual-screenshots:/code/cypress-visual-screenshots
      - ./cypress-visual-report:/code/cypress-visual-report
      - ./cypress/videos:/code/cypress/videos
      - ./src:/code/src
