# fly.toml file generated for scolaire on 2023-01-12T10:08:50+04:00

app = "scolaire"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  VITE_XANO_URL= "https://x8ki-letl-twmt.n7.xano.io/api:DL_gv4vw"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8043
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
