#!/bin/bash

echo "****** Launch test *********"

script_directory=$(dirname $(readlink -f $0))
# TODO: exécuter les commande docker depuis le dossier ./cypress
cd $script_directory

docker-compose build
docker-compose up
