version: "3.2"

services:
  cypress:
    build:
      context: ..
      dockerfile: cypress/Dockerfile
    command: npm run cypress-watch

    volumes:
      - ./:/code/cypress
      - ../src:/code/src
      - ../tailwind.config.js:/code/tailwind.config.js
      - ../cypress.config.ts:/code/cypress.config.ts
