version: "3.2"

services:
  cypress:
    stdin_open: true
    tty: true
    build:
      context: ..
      dockerfile: cypress/Dockerfile

    volumes:
      - ./:/code/cypress
      - ../src:/code/src
      - ../tailwind.config.js:/code/tailwind.config.js
      - ../cypress.config.ts:/code/cypress.config.ts
