version: "3.2"

services:
  cypress:
    build:
      context: ..
      dockerfile: cypress/Dockerfile
    command: npm run cypress-watch

    volumes:
      - ./:/code/cypress
      - ../src:/code/src
      - ../testing:/code/testing
      - ../tailwind.config.js:/code/tailwind.config.js
      - ../.storybook/utils:/code/.storybook/utils
