name: "Cypress Tests"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

jobs:
  cypress-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and run services
        run: ./cypressAction.sh
