name: "Cypress Tests"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"
#TODO fixer la version de ubuntu
jobs:
  cypress-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run cypress test console and graphic (snapshot)
        run: ./cypress-github-action
